
title: Blogin
email: blogin@example.com
description: "A simple blog site"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 2
paginate_path: "/posts/page:num/"

# Build settings
markdown: kramdown
permalink: /articles/:title
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Includes
include: ['_pages']
